
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 256280414173-ao03irqngbolji4ula5pmqa78e46tesn.apps.googleusercontent.com
            client-secret: P3z9BSTTeMpejbSnS16hKV7f
            scope:
            - email
            - profile

          facebook:
            client-id: 2900027036953220
            client-secret: 59bc5f2c9ad228c102d2805a43ba9734
            scope:
            - email
            - public_profile
          
          naver:
            client-id: Akvrsz2Y6xQTpM9tXT2M
            client-secret: XwxjvjrF_V
            scope:
            - id
            - email
            - name
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: Naver
          
          kakao:
            client-id: f9670e14cdc75cfd2328e79b7b733af7
            client-secret: hfDjSvr2Nt2VjXsFMorrDODtTN3nJSm9
            scope:
            - profile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST
                    provider:          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
           
            



